children: [
    {
      id: 259,
      name: 'امام حسن',
      slug: 'imam-hasan',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '259',
      },
      lat: '29.837507',
      lon: '50.263188',
    },
    {
      id: 260,
      name: 'انارستان',
      slug: 'anarestan',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '260',
      },
      lat: '28.032648',
      lon: '52.063887',
    },
    {
      id: 261,
      name: 'اهرم',
      slug: 'ahram',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '261',
      },
      lat: '28.884114',
      lon: '51.275618',
    },
    {
      id: 262,
      name: 'آب پخش',
      slug: 'ab-pakhsh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '262',
      },
      lat: '29.366763',
      lon: '51.070032',
    },
    {
      id: 263,
      name: 'آبدان',
      slug: 'abdan',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '263',
      },
      lat: '28.077508',
      lon: '51.770904',
    },
    {
      id: 264,
      name: 'برازجان',
      slug: 'borazjan',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '264',
      },
      lat: '29.269284',
      lon: '51.216502',
    },
    {
      id: 265,
      name: 'بردخون',
      slug: 'bordkhun',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '265',
      },
      lat: '28.031095',
      lon: '51.457150',
    },
    {
      id: 266,
      name: 'بندردیر',
      slug: 'bandar-dayyer',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '266',
      },
      lat: '27.843479',
      lon: '51.936609',
    },
    {
      id: 267,
      name: 'بندردیلم',
      slug: 'bandar-deylam',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '267',
      },
      lat: '30.060303',
      lon: '50.163252',
    },
    {
      id: 268,
      name: 'بندرریگ',
      slug: 'bandar-rig',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '268',
      },
      lat: '29.485289',
      lon: '50.630848',
    },
    {
      id: 269,
      name: 'بندرکنگان',
      slug: 'bandar-kangan',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '269',
      },
      lat: '27.833812',
      lon: '52.073982',
    },
    {
      id: 270,
      name: 'بندرگناوه',
      slug: 'bandar-ganaveh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '270',
      },
      lat: '29.583560',
      lon: '50.512003',
    },
    {
      id: 271,
      name: 'بنک',
      slug: 'banak',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '271',
      },
      lat: '27.863435',
      lon: '52.016144',
    },
    {
      id: 272,
      name: 'بوشهر',
      slug: 'bushehr',
      isCapital: '1',
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '272',
      },
      lat: '28.92338370',
      lon: '50.82031400',
    },
    {
      id: 273,
      name: 'تنگ ارم',
      slug: 'tange-eram',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '273',
      },
      lat: '29.152236',
      lon: '51.528196',
    },
    {
      id: 274,
      name: 'جم',
      slug: 'jam',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '274',
      },
      lat: '27.8122053',
      lon: '52.3507118',
    },
    {
      id: 275,
      name: 'چغادک',
      slug: 'choghadak',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '275',
      },
      lat: '28.983428',
      lon: '51.021653',
    },
    {
      id: 276,
      name: 'خارک',
      slug: 'khark',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '276',
      },
      lat: '29.2601804',
      lon: '50.3288332',
    },
    {
      id: 277,
      name: 'خورموج',
      slug: 'khormoj',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '277',
      },
      lat: '28.652324',
      lon: '51.383228',
    },
    {
      id: 278,
      name: 'دالکی',
      slug: 'dalaki',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '278',
      },
      lat: '29.430197',
      lon: '51.291035',
    },
    {
      id: 279,
      name: 'دلوار',
      slug: 'delvar',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '279',
      },
      lat: '28.754527',
      lon: '51.067886',
    },
    {
      id: 280,
      name: 'ریز',
      slug: 'riz',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '280',
      },
      lat: '28.052363',
      lon: '52.072127',
    },
    {
      id: 281,
      name: 'سعدآباد',
      slug: 'saadabad',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '281',
      },
      lat: '29.386886',
      lon: '51.118226',
    },
    {
      id: 282,
      name: 'سیراف',
      slug: 'siraf',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '282',
      },
      lat: '27.668780',
      lon: '52.343545',
    },
    {
      id: 283,
      name: 'شبانکاره',
      slug: 'shabankareh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '283',
      },
      lat: '29.470517',
      lon: '50.990682',
    },
    {
      id: 284,
      name: 'شنبه',
      slug: 'shanbeh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '284',
      },
      lat: '28.396317',
      lon: '51.762836',
    },
    {
      id: 285,
      name: 'عسلویه',
      slug: 'asaluyeh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '285',
      },
      lat: '27.475912',
      lon: '52.612603',
    },
    {
      id: 286,
      name: 'کاکی',
      slug: 'kaki',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '286',
      },
      lat: '28.341930',
      lon: '51.521373',
    },
    {
      id: 287,
      name: 'کلمه',
      slug: 'koleme',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '287',
      },
      lat: '28.940626',
      lon: '51.459671',
    },
    {
      id: 288,
      name: 'نخل تقی',
      slug: 'nakhl-taghi',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '288',
      },
      lat: '27.501354',
      lon: '52.584626',
    },
    {
      id: 289,
      name: 'وحدتیه',
      slug: 'vahdatiyeh',
      isCapital: '0', province_id: 7,
      districts: [],
      allowedToFilterByDistrict: false,
      ownCity: {
        type: 13,
        title: 'فقط شهر خودم',
        analyticsKey: 'mycity_tab',
        query: 'hai=1',
        id: '289',
      },
      lat: '29.486601',
      lon: '51.235556',
    },
  ],